In [1]:
import numpy as np

In [3]:
#initiate array object


#np.array()

#array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

#object - array type object
#dtype = data type of object
#order = C(row major) / F(column major) / K(any)
#subok = True means subclasses pass through
#ndim = dimension of resultant array

In [8]:
#examples

a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
print(a)#no commas in between

[1 2 3]


In [14]:
#more than one dimension

b = np.array([[1,2],
            [3,4]])
print(b)

[[1 2]
 [3 4]]


In [15]:
b

array([[1, 2],
       [3, 4]])

In [2]:
#ndim specified
c = np.array([1,2,3,4,5],ndmin=3)
c

array([[[1, 2, 3, 4, 5]]])

In [27]:
#dtype specified
d = np.array([1,2,3,4,5],ndmin=2,dtype='complex')
d

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]])

In [30]:
#subok specified
e = np.array(np.mat('1 2; 3 4'),subok=False)
e

array([[1, 2],
       [3, 4]])

In [31]:
f = np.array(np.mat('1 2; 3 4'),subok=True)
f

matrix([[1, 2],
        [3, 4]])

In [32]:
#defining of ndarray using specific dtype
#using scalar object
dt = np.dtype(np.int64)
dt

dtype('int64')

In [34]:
#structured data
dt = np.dtype([('age',np.int8)])
dt

dtype([('age', 'i1')])

In [37]:
#applying same to ndarray object
dt = np.dtype([('age',np.int8)])
a =np.array([(10),(20),(30)],dtype=dt)
print(a['age'])
#print(a)

[10 20 30]


In [39]:
#multi dimensional data
dt = np.dtype([('name','S20'),('age','i8'),('marks','float16')])


[('name', 'S20'), ('age', '<i8'), ('marks', '<f2')]


In [42]:
a = np.array([('abc',21,80),('adf',51,78)],dtype=dt)
a

array([(b'abc', 21, 80.), (b'adf', 51, 78.)],
      dtype=[('name', 'S20'), ('age', '<i8'), ('marks', '<f2')])

In [43]:
print(a)

[(b'abc', 21, 80.) (b'adf', 51, 78.)]


In [44]:
#Array Attributes

#shape

#ndarray.shape
 #it returns tuple containing the array dimensions this can be used to resize the array
    
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [45]:
a.shape

(2, 3)

In [46]:
a.shape = (3,2)

In [47]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
a.shape

(3, 2)

In [49]:
#reshape
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
#ndim
print(a.ndim)

2


In [53]:
#itemsize

#numpy.itemsize returns the length of each element of array in bytes

a.itemsize

4

In [55]:
#empty

#np.empty()
#empty(shape, dtype=float, order='C')
#fills all with garbage values
s = np.empty(shape=(3,),dtype=int,order='C')
s

array([95791872,      566,        0])

In [56]:
#numpy.Zeros  #numpy.ones

#returns the array with specific size all values initialized to zero

x = np.zeros(shape=(3,2),dtype=float)
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
#asarray

#used for converting python sequence to ndarray

x = [1,2,3]
a = np.asarray(x)
a

array([1, 2, 3])

In [62]:
x = [(1,2,3),(4,5)]
y = np.asarray(x)
y.shape


(2,)

In [63]:
#fromiter

#builds ndarray object from iterable object

#np.fromiter()

#fromiter(iterable, dtype, count=-1)

#count = -1 number of items to read from iterator default = -1 meaning all

In [65]:
list_ = range(1,10)
it = iter(list_)

x = np.fromiter(it,dtype=int,count=5)
print(x)

[1 2 3 4 5]


In [66]:
#arange

#np.arange()

#arange([start,] stop[, step,], dtype=None)

x = np.arange(40)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [67]:
y = np.arange(1,40,5)
y

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [68]:
#linspace

#np.linspace()

#np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)

#num = number of elements evenly spaced

x = np.linspace(start=10,stop=20,num=5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [69]:
#indexing and slicing

#using slice operator

a = np.arange(0,10)
s = slice(2,7,2)
print(a[s])

[2 4 6]


In [6]:
#indexing using elipsis(...)
a = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
a[...]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [74]:
a[...,1]

array([2, 5, 8, 2])

In [77]:
a[...,2]

array([3, 6, 9, 3])

In [79]:
a[...,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [81]:
a[1:,...]

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [83]:
#integer indexing
x= np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[1,0,1]] #x[row_index,column_index]
#0,0
#1,0
#2,1
y

array([2, 3, 6])

In [86]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[1,4,5]])
rows = np.array([[0,0],[1,2]])
cols = np.array([[1,1],[1,2]])

y = x[rows,cols]
y  #to print in 2d array

array([[2, 2],
       [5, 9]])

In [87]:
y = x[1:4,[1,2]]
y

array([[5, 6],
       [8, 9],
       [4, 5]])

In [88]:
#boolean slicing  


print(x[x>5])

[6 7 8 9]


In [2]:
#broadcasting

#same dimension

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a*b)


[ 4 10 18 28]


In [3]:
#different dimensions
c = np.array([[1,2,3,4],[7,8,9,4]])
print(a*c)

[[ 1  4  9 16]
 [ 7 16 27 16]]


In [2]:
#broadcasting rules

#size of each dimensions should be same
#size of one dimension should be 1
 
    
#rule 1 : if two arrays differ in their number of dimension the shape of one with fewer dimension is padded with ones on its leading side(left side)
#rule2 : if shape of two arrays does not match in any dimension the array with shape equal to 1 in that dimension is stretched to match other shape
#rule3 : if in any dimension the sizes disagree and neither equal to 1 an error is raised.

a = np.array([1,2,3,4])
b = np.array([1,2,3])
a+b  #rule3

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
a+b

array([[2, 4],
       [4, 6]])

In [2]:
r = np.random.randn(2,4)#normal distribution
s = np.random.rand(1,3)#uniform distribution

In [4]:
#iterating over array

#nditer

a = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [7]:
for i in np.nditer(a,order='F'):
    print(i)

1
4
2
5
3
6


In [10]:
#op_flags default is read only it can be readwrite
for i in np.nditer(a,op_flags = ['readwrite']):
    i[...] = 2*i

In [11]:
print(a)

[[128 128 128]
 [128 128 128]]
